import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Providers from '@/components/Providers'
import Footer from '@/components/sections/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Web Zeppelin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
