import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/components/Providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Web Zeppelin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
